# Generated by Django 2.2.3 on 2022-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20220208_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
